#!/bin/sh

set -e

extDir=$(php -r 'echo ini_get("extension_dir");')

modules=
for module; do
  [[ "" != "$module" ]] && {
    php -m | grep $module || modules="$modules $module"
  }
done
[[ "" = "$modules" ]] && exit 0

xmodules=
for module in $modules; do
  mod=$(echo $module | sed -E 's/\-[^ ]+//g')
  php -m | grep -iq $mod || docker-php-ext-enable $mod >/dev/null 2>&1 || true
  { ls $extDir/$mod.so >/dev/null 2>&1 && echo "$module already installed"; } \
    || { [[ "" != "$xmodules" ]] && xmodules="$xmodules $module" || xmodules="$module"; }
done
[[ "" = "$xmodules" ]] && exit 0

echo "docker-php-ext-install $xmodules"
yes '' | MAKEFLAGS="-j $(nproc)" docker-php-ext-install -j "$(nproc)" $xmodules
