#!/bin/sh

set -e

extDir=$(php -r 'echo ini_get("extension_dir");')

usage() {
  echo "usage: $0 [options] module-name [module-name ...]"
  echo "   ie: $0 apcu"
  echo "       $0 apcu redis"
  echo

  exit 1
}

modules=
for module; do
  [[ "$module" == "--help" ]] || [[ "$module" == "-h" ]] && usage >&2
  [[ -n "$modules" ]] && modules="$modules $module" || modules="$module"
done
[[ "" = "$modules" ]] && exit 0

xmodules=
for module in $modules; do
  mod=$(echo $module | sed -E 's/\-[^ ]+//g')
  php -m | grep -iq $mod || docker-php-ext-enable $mod >/dev/null 2>&1 || true
  { ls $extDir/$mod.so >/dev/null 2>&1 && echo "$module already installed"; } \
    || { [[ "" != "$xmodules" ]] && xmodules="$xmodules $module" || xmodules="$module"; }
done
[[ "" = "$xmodules" ]] && exit 0

echo "MAKEFLAGS='-j $(nproc)' pecl install $xmodules"
yes '' | MAKEFLAGS="-j $(nproc)" pecl install $xmodules
