name: build_preview

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "[8.3r] Build and push"
        id: docker_build_83
        uses: docker/build-push-action@v4
        with:
          push: true
          file: 8.3.Dockerfile
          tags: adhocore/phpfpm:8.3r,adhocore/phpfpm:8.3rc
          platforms: linux/amd64,linux/arm64
